// control + letters
#define KEYS_CTRL_A 1
#define KEYS_CTRL_B 2
#define KEYS_CTRL_C 3
#define KEYS_CTRL_D 4
#define KEYS_CTRL_E 5
#define KEYS_CTRL_F 6
#define KEYS_CTRL_G 7
#define KEYS_CTRL_H 8
#define KEYS_CTRL_I 9
#define KEYS_CTRL_J 10
#define KEYS_CTRL_K 11
#define KEYS_CTRL_L 12
#define KEYS_CTRL_M 13
#define KEYS_CTRL_N 14
#define KEYS_CTRL_O 15
#define KEYS_CTRL_P 16
#define KEYS_CTRL_Q 17
#define KEYS_CTRL_R 18
#define KEYS_CTRL_S 19
#define KEYS_CTRL_T 20
#define KEYS_CTRL_U 21
#define KEYS_CTRL_V 22
#define KEYS_CTRL_W 23
#define KEYS_CTRL_X 24
#define KEYS_CTRL_Y 25
#define KEYS_CTRL_Z 26

// capital letters
#define KEYS_SHIFT_A 65
#define KEYS_SHIFT_B 66
#define KEYS_SHIFT_C 67
#define KEYS_SHIFT_D 68
#define KEYS_SHIFT_E 69
#define KEYS_SHIFT_F 70
#define KEYS_SHIFT_G 71
#define KEYS_SHIFT_H 72
#define KEYS_SHIFT_I 73
#define KEYS_SHIFT_J 74
#define KEYS_SHIFT_K 75
#define KEYS_SHIFT_L 76
#define KEYS_SHIFT_M 77
#define KEYS_SHIFT_N 78
#define KEYS_SHIFT_O 79
#define KEYS_SHIFT_P 80
#define KEYS_SHIFT_Q 81
#define KEYS_SHIFT_R 82
#define KEYS_SHIFT_S 83
#define KEYS_SHIFT_T 84
#define KEYS_SHIFT_U 85
#define KEYS_SHIFT_V 86
#define KEYS_SHIFT_W 87
#define KEYS_SHIFT_X 88
#define KEYS_SHIFT_Y 89
#define KEYS_SHIFT_Z 90

// lowercase letters
#define KEYS_A 97
#define KEYS_B 98
#define KEYS_C 99
#define KEYS_D 100
#define KEYS_E 101
#define KEYS_F 102
#define KEYS_G 103
#define KEYS_H 104
#define KEYS_I 105
#define KEYS_J 106
#define KEYS_K 107
#define KEYS_L 108
#define KEYS_M 109
#define KEYS_N 110
#define KEYS_O 111
#define KEYS_P 112
#define KEYS_Q 113
#define KEYS_R 114
#define KEYS_S 115
#define KEYS_T 116
#define KEYS_U 117
#define KEYS_V 118
#define KEYS_W 119
#define KEYS_X 120
#define KEYS_Y 121
#define KEYS_Z 122

// extra keys
#define KEYS_ESC 27
#define KEYS_ENTER 10
#define KEYS_TICK 96
#define KEYS_TILDE 126

// arrow keys
#define KEYS_UP 259
#define KEYS_DOWN 258
#define KEYS_LEFT 260
#define KEYS_RIGHT 261
